feat: bash script to trigger other workflow files
cncf-tags/green-reviews-tooling pull request #106
Opened 2024-06-19 17:46 UTC by dipankardas011

#### What type of PR is this?
kind/feature

#### What this PR does / why we need it:
- Improvises on #104 

#### Which issue(s) this PR fixes:
- Fixes #98

#### Special notes for your reviewer (optional):

2024-06-19 18:10 UTC, dipankardas011 commented
Only place left for testing this script is workflow_dispatch with 2 types of workflows which can have sub_components or not have it

also need to think of do we send one sub_component at a time or all at once like a json array or a string with each having its individual workflow_call?

2024-06-20 17:30 UTC, rossf7 requested changes
@dipankardas011 Thank you the approach here using bash works a lot better.

Some changes still needed. Especially the output to the console which can be much simpler.

2024-06-20 17:30 UTC, rossf7 commented on .gitignore
> +.idea
Needs a rebase. These lines were removed.

2024-06-20 17:30 UTC, rossf7 commented on scripts/project-trigger.sh
> +    echo "[ERR] GH_TOKEN not set"
```suggestion
    echo "GH_TOKEN not set"
```

Some output is important but lets keep it as simple as possible. 

We don't need these prefixes so pls remove them from all the echo statements. If its an error the echo text should explain that.

2024-06-20 17:30 UTC, rossf7 commented on scripts/project-trigger.sh
> +    # TODO(dipankar): need to make the cncf_project_sub to be each individiual call for each sub-component
Yes, this still needs to be implemented.

2024-06-20 17:30 UTC, rossf7 commented on .github/workflows/project-trigger.yml
> +    - cron: '0 0 * * 0'
```suggestion
    - cron: '0 0 * * *'
```

We changed design to run daily rather than weekly.

2024-06-20 17:30 UTC, rossf7 commented on scripts/project-trigger.sh
> +    echo "-----------------------------"
```suggestion
    echo "workflow_call event [proj: $proj_name]=> $workflow_dispatch"
```

2024-06-20 17:40 UTC, rossf7 commented on scripts/project-trigger.sh
> +    # TODO(dipankar): need to make the cncf_project_sub to be each individiual call for each sub-component
> also need to think of do we send one sub_component at a time or all at once like a json array or a string with each having its individual workflow_call?

The benchmark-pipeline action needs to be called once per subcomponent if they exist.

Its an array in the projects.json so can you loop through each component? 

If there are no sub components you could pass an empty string.

2024-06-23 06:04 UTC, dipankardas011 commented
@rossf7 Should I add color for error logs?

2024-06-24 14:48 UTC, rossf7 reviewed
> @rossf7 Should I add color for error and success logs?

@dipankardas011 No that isn't necessary and makes the code more complex.

Pls revert the changes in 129d1105b09e97ee048d1aca110c549e77a3f691

Better to focus on making sure the text in the echo statements is clear. I suggested a couple of edits and then this is good to go

2024-06-24 16:47 UTC, dipankardas011 commented on scripts/project-trigger.sh
> +        echo "No sub-components for $proj_name. Performing certain task..."
Done

2024-06-24 16:47 UTC, dipankardas011 commented on scripts/project-trigger.sh
> +        echo "$proj_name has sub-components. Performing tasks for each sub-component..."
Done

2024-06-24 17:02 UTC, rossf7 approved these changes
LGTM 💚

2024-06-24 17:02 UTC, merged

2024-06-25 02:30 UTC, dipankardas011 commented
> LGTM 💚

But the env var for the gh_pat token?

2024-06-25 12:39 UTC, rossf7 commented
> But the env var for the gh_pat token?

@dipankardas011 We need to open a service desk ticket to request a new token. I'll take care but will need some help from the other leads.

2024-06-26 14:17 UTC, rossf7 commented
@dipankardas011 Token is added as a secret and working well here.
https://github.com/cncf-tags/green-reviews-tooling/issues/7#issuecomment-2189406546

Nice job! 🚀 

There is an issue with the deploy step itself. Will debug that later